services:
  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - backend

  # Node.js Backend
  backend:
    build:
      context: ./backend1
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASS=jonas1385
      - DB_NAME=simplyinvite
      - NODE_ENV=development
      - PORT=8080
    networks:
      - app-network
    depends_on:
      - postgres
    volumes:
      - ./backend1:/usr/src/app
      - /usr/src/app/node_modules

  # PostgreSQL Database
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=jonas1385
      - POSTGRES_DB=simplyinvite
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
